### ISSUE TITLE
line with gallery path above resource form

### ISSUE THREAD

**Issue by florian-rabis** [donShakespeare/TinymceWrapper#1]
Hey,
since the last update to version 2.3 I get the following line output above my resource edit form.
I'm not sure if this is a bug or a misconfiguration maybe of my file permissions. The last days I had some problems with my provider.

Can you please check this out?

![screenshot from 2016-03-10 22 03 23](https://cloud.githubusercontent.com/assets/15198883/13684529/6a1c36a4-e70c-11e5-9301-715f8ea098b3.png)

Best regards
Florian

PS: Thank you very much for your great work. You saved my life. The old TinyMCE plugin was just a disaster.

Edit:
Ok I did a quick reinstall after changing the file permissions to 777 and now the TinyMCE won't load.

![screenshot from 2016-03-10 22 16 41](https://cloud.githubusercontent.com/assets/15198883/13684887/1eb62362-e70e-11e5-9573-ad8aeef49f5f.png)

**Comment by donShakespeare** [comment]
Hello Florian,
I am happy you have found TinymceWrapper useful.
> line with gallery path above resource form 

There is a known incompatibility with Image+ Extra.
Do you have that installed? Maybe it is also incompatible with Gallery.
Try disabling those two plugins.

>Ok I did a quick reinstall after changing the file permissions to 777 and now the TinyMCE won't load.

If you check your browser errors, you will see that TinyMCE loads but the stylesheet did not.
Please do a clean removal, and then reinstall. Or hard refresh your browser ... + clear MODX cache

**Comment by Jako** [comment]
Something triggers this line (on my test installation a line with formz is shown `/…/core/components/formz/processors/mgr/tv/output/` if the OnDocFormPrerender plugin event of TinyMCEWrapper is active.

The html source at the end of the manager page shows the following lines 
```
 <div class="clear"></div>
</div>

/…/core/components/formz/processors/mgr/tv/output/
    </div>
    <!-- #modx-content-->
    <div id="modx-footer"></div>
</div>
<!-- #modx-container -->

</body>
</html>
```

**Comment by Jako** [comment]
It is call of $resource->getTVValue($tvId); in line 162 of tinymcewrapper.plugin.php (the current version seems not to be commited to this repository).

This triggers the `OnTVOutputRenderList` event which causes the output. You have to modify that line and get the value somehow else. A getObject example could be found on: https://rtfm.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/template-variables/accessing-template-variable-values-via-the-api

**Comment by florian-rabis** [comment]
> OR if you are not using TinymceWrapper's TinyJSONGallery - you can disable it in the TinymceWrapper Plugin's properties enableImageGallery

That works for me. Thank you. I need the gallery plugin and I know about its weaknesses. But at the moment its enough.
