### ISSUE TITLE
TinyMCE just load partially

### ISSUE THREAD

**Issue by florian-rabis** [donShakespeare/TinymceWrapper#2]
Hey,
yesterday I got a new problem. The TinyMCE now loads just partially. I didn't take any changes on my configuration.
Where could be caused this problem?
![bildschirmfoto vom 2016-08-01 09 50 40](https://cloud.githubusercontent.com/assets/15198883/17287268/ee90528e-57ce-11e6-97b9-8a6462414878.jpg)

I got this on all Installations I have running. So under modx revolution 2.4.3 as well as under 2.5.0.
Everywhere I installed the latest version of the TinyMCEWrapper. I seems that it's not caused by the browser. I tested it in firefox and in chromium and I got the same issue in both browsers.

I hope you can help me.

**Comment by donShakespeare** [comment]
Error reported and solved here.
https://forums.modx.com/thread/97694/support-comments-for-tinymcewrapper?page=26#dis-post-542429

It's a TinyMCE plugin of mine that went awry when the TinyMCE CDN was updated.
**Find** my updated plugin,
https://github.com/donShakespeare/modxMagicHoverLink
**Replace** in assets/comp.../tiny.../tinymceplugins/

I'll be sending out a new release, so issue should go away

**Comment by donShakespeare** [comment]
See latest update TinymceWrapper 2.3.2-pl

https://forums.modx.com/thread/97694/support-comments-for-tinymcewrapper?page=27#dis-post-543737

http://modx.com/extras/package/tinymcewrapper
